### ISSUE TITLE
sbt pdf fails due to Incomplete \iffalse

### ISSUE THREAD

**Issue by chpache** [lunduniversity/introprog#450]
Hello everyone,
I'm trying to build the documentation locally but it fails on compendium,labs and exerices with the following output.
I wonder if it might be due to macro including too much of code (following some searches I did). Is there any configuration to be done prior to `sbt pdf` ? Do you know where this might come  from?

Many thanks for any information,
Christophe

```[49]
Overfull \hbox (5.12372pt too wide) in paragraph at lines 203--204
[]\T1/fnc/m/n/13 K�r ditt pro-gram med den \T1/fnc/m/it/13 gula \T1/fnc/m/n/13 
play-knappen. Stu-dera hur an-rop av pro-ce-du-ren [][][]
[50] [51
! Incomplete \iffalse; all text was ignored after line 254.
<inserted text> 
                \fi 
l.254 def 
          move(key: Int): Unit = {
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on compendium.log.
[error] java.lang.RuntimeException: 
[error] *** ERROR: pdflatex exit code: 1
[error] See COMPLETE pdflatex output in: compendium/compendium-console.log
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at $9cae5408bd7dafc36a01$.runPdfLatexCmd(build.sbt:93)
[error] 	at $714619f152cebf8c8bbf$.$anonfun$$sbtdef$1(/home/chpache/Documents/home/introprog/build.sbt:112)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (pdf) 
[error] *** ERROR: pdflatex exit code: 1
[error] See COMPLETE pdflatex output in: compendium/compendium-console.log
[error] Total time: 66 s, completed Jan 21, 2020 2:13:00 PM
```

**Comment by bjornregnell** [comment]
@chpache This seems to be a latex error and not to do with sbt or setup. I suspect this might be due to differences in latex version but I'm not sure. I'm closing this for now, but let me know if the error occurs again and we might hunt it down. Let me then know on which system you are running etc. and we will try to understand under what circumstances the bug arises.

**Comment by chpache** [comment]
thanks @bjornregnell
